[package]
name = "bricklehampton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
radon = "0.1.0"
rayon = "1.10.0"
